name: CI

on:
  push:
    branches: 'main'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 20.10
        uses: actions/setup-node@v1
        with:
          node-version: 20.10
      - run: npm i
      - run: npm run build-prod
      - run: npm run lint
      - run: npm run test-once
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./dist
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.1.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          format: 'markdown'
          output: 'both'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Publish to npm
        if: ${{ github.event_name != 'pull_request' }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: './dist/package.json'
